### ISSUE TITLE
Unable to set up project for local development

### ISSUE THREAD

**Issue by LostSputnik** [ruxailab/web-eye-tracker#12]
I have been trying to set up the eye-tracker front-end and back-end but to no avail. 
### For the web-eye-tracker repo, I have:
1. pulled from develop branch
1. created a firebase project, added a firestore db, and put the values from key.json to the env variable

### For the web-eye-tracker-front, I have:
1. pulled from the main (same as develop so far) branch
1. installed the dependencies and ran in development mode

I open the app in localhost. Then, in the login screen where it says Login with Google to start creating your usability tests I click on sign in with google but nothing happens. This is the error i get in console:

![image](https://github.com/ruxailab/web-eye-tracker/assets/34897621/65c6c2e6-867b-4719-a957-08a081fa6dc4)

Any help would be very much appreciated. I've been at this for quite some time now, wanting to explore the ML model and how it integrates with the tracker. Thanks.

**Comment by hvini** [comment]
the web eye traker app do not require firebase credentials anymore, instead,  you can add the credentials on web eye tracker front. take a look on front readme to see which values are required and which are the keys for the values.

https://github.com/ruxailab/web-eye-tracker-front

**Comment by LostSputnik** [comment]
thanks for that. Took me a while but I was finally able to run calibration on my local environment.
